# Dependencies
  markdown:         redcarpet
  pygments:         true

# Permalinks
  permalink:        pretty

# Setup
  title:            Plainspace
  tagline:          'A Jared Volpe thing'
  description:      'Leading Product Design @ Leap Motion.'
  url:              http://plainspacedesign.com

author:
  name:             'Jared Volpe'
  url:              https://twitter.com/plainspace

  paginate:         5

# Custom vars
  version:          1.0.0

github:
  repo:             https://github.com/plainspace/